CREATE TABLE Folders (
	idStorage INTEGER NOT NULL,
	idFolder INTEGER NOT NULL,
	Name VARCHAR(15) NOT NULL,
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY (idStorage) REFERENCES Storage(id)
);

CREATE TABLE Files (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	idFolder INTEGER NOT NULL ,
	Name VARCHAR(15) NOT NULL ,
	idMessage INTEGER NOT NULL ,
	idChat INTEGER NOT NULL ,
	idFileAPI VARCHAR(200) NOT NULL,
	FSCreatedTime VARCHAR(20) NOT NULL,
	FSAccessTime VARCHAR(20) NOT NULL,
	FSWriteTime VARCHAR(20) NOT NULL,
	FSHash VARCHAR(100),
	FOREIGN KEY (idFolder) REFERENCES Folders(id)
);

CREATE TABLE User (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	Name VARCHAR(300) NOT NULL,
	idChat INTEGER NOT NULL
);


CREATE TABLE Storage (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	Name VARCHAR(15) NOT NULL ,
	idUser INTEGER NOT NULL ,
	idShared VARCHAR(300) NOT NULL ,
	FOREIGN KEY (idUser) REFERENCES User(id)
);


CREATE TRIGGER foldersBeforeDelete
BEFORE DELETE
   ON Folders FOR EACH ROW

BEGIN
	DELETE FROM Files WHERE idFolder = OLD.id;
END; 


CREATE TRIGGER storageBeforeDelete
BEFORE DELETE
   ON Storage FOR EACH ROW

BEGIN
	DELETE FROM Folders WHERE idStorage = OLD.id;
END; 